### ISSUE TITLE
I'm using ffmpeg for hard decoding under Android and I'm having some problems, can you help me with this? Thank you very much!

### ISSUE THREAD

**Issue by djhdj1** [bmegli/hardware-video-decoder#16]
I have read your code, but I still don't understand how to use FFMPEG for hard decoding with Mediacodec under Android. According to your instructions, do I need to assign values to extradata, extradata_size, width, height under AVCodecContext type, and then I can hard decoding? After I manually assign these variables correctly, "avcodec_open2" does not return -1 anymore and the hard decoding is initialized successfully. But when "avcodec_send_packet" starts, there is a crash.`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 23119`, logcat `null pointer dereference`
I don't know what the problem is, thank you very much

**Comment by bmegli** [comment]
> I have read your code, but I still don't understand how to use FFMPEG for hard decoding with Mediacodec under Android.

There is no support for Mediacodec in this library.

> According to your instructions, do I need to assign values to extradata, extradata_size, width, height under AVCodecContext type, and then I can hard decoding?

Which instructions? There are no instructions here. Only closed issue from years ago with experiment marked with `wontfix` (will not fix)
- https://github.com/bmegli/hardware-video-decoder/issues/5

Experiment ended up with partial success. All gathered information is in above issue.

The last experiment is in 087041cd which is not on master branch.

This is not official or documented FFmpeg way to do it, just my guesswork. Nothing guarantees that it will work.
